name: AuthN Server

on:
  push:
    branches:
      - master
    paths:
      - authn-server/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          # optional (defaults to `postgres`)
          POSTGRES_DB: postgres
          # required
          POSTGRES_PASSWORD: postgres
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Package
        run: |
          cd authn-server
          mvn -B compile --file pom.xml
          mvn -B test-compile --file pom.xml
      - name: JUnits
        run: |
          cd authn-server
          mvn -B test --file pom.xml
      - name: Integration Test
        run: |
          cd authn-server
          mvn -B verify -Pintegration-tests --file pom.xml